### ISSUE TITLE
[APP] Ошибка при деплое java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by anry-das** [Viencer/Hospital#5]
При деплое вылазит ошиибка
```
java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException
	at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
	at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:1029)
	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:990)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:104)
	at weblogic.utils.classloaders.GenericClassLoader.doFindClass(GenericClassLoader.java:611)
	at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:543)
	Truncated. see log file for complete stacktrace
```

**Comment by Viencer** [comment]
Проверял на двух ноутбуках и одном ПК, вроде, нету такой ошибки. Возможно, она пропала после устранения остальных ошибок.

**Comment by Viencer** [comment]
Проблему, пока что, не закрываю

**Comment by Viencer** [comment]
17d49bf81f37999e80d675141ddd058bb1bc42fb Добавил одну зависимость. Возможно, поможет.
